# https://hub.docker.com/_/ros/
image: ros:kinetic-ros-core

variables:
  # If package name is "ros-kinetic-actionlib" it becomes "actionlib" (remove the prefix)
  ROS_PACKAGES_TO_INSTALL: "actionlib" # Here the package is useless, it is just for demonstration
  SELF_TEST: "true" # Do not set this variable in your packages!

before_script:
 - git clone https://gitlab.com/VictorLamoine/ros_gitlab_ci.git
 - ros_gitlab_ci/gitlab-ci.bash

catkin_make:
  stage: build
  script:
    - catkin_make

catkin_build:
  stage: build
  script:
    - catkin build

